import OperationsCore
import SwiftUI

struct AcquireView:View {
    @EnvironmentObject var store:ConsoleStore;@State private var asset="AUDUSD";@State private var from="2026-07-01";@State private var through="2026-07-10";@State private var mode=ConflictMode.preserve;@State private var reviewing=false
    var body:some View{ScrollView{VStack(alignment:.leading,spacing:18){Text("Acquire").font(.largeTitle);Text("Explicit bounded Twelve Data acquisition through the registered CLI writer.").foregroundStyle(.secondary);Form{TextField("Asset",text:$asset).textFieldStyle(.roundedBorder);LabeledContent("Timeframe",value:"D1");TextField("From date",text:$from);TextField("Inclusive through date",text:$through);Picker("Conflict mode",selection:$mode){ForEach(ConflictMode.allCases,id:\.self){Text($0.rawValue.capitalized)}};LabeledContent("Provider",value:"TWELVE_DATA");LabeledContent("Contract",value:"TWELVE_DATA_TIME_SERIES_D1_V1");LabeledContent("Credential",value:store.credentialAvailable ? "Available (redacted)":"Unavailable");LabeledContent("Database",value:store.databasePath)};Button("Review Acquisition"){reviewing=true}.buttonStyle(.borderedProminent).disabled(!store.credentialAvailable || store.activeOperationID != nil);ResultPanel()}.padding().frame(maxWidth:760,alignment:.leading)}.onAppear{if let prefill=store.acquisitionAsset{asset=prefill;store.acquisitionAsset=nil}}.confirmationDialog("Review Acquisition",isPresented:$reviewing,titleVisibility:.visible){Button("Run Acquisition"){Task{await store.run(.acquire(asset:asset,from:from,through:through,mode:mode))}};Button("Cancel",role:.cancel){}}message:{Text("Provider: Twelve Data\nLane: \(asset) D1\nRange: \(from) through \(through) inclusive\nMode: \(mode.rawValue)\nDatabase: \(store.databasePath)")}}
}

struct ResultPanel:View{@EnvironmentObject var store:ConsoleStore;var body:some View{if let r=store.lastProcessResult{GroupBox("Latest operation \(r.operationID.uuidString)"){VStack(alignment:.leading){Text("Exit \(r.exitCode)");Text(r.stdout).font(.caption.monospaced()).textSelection(.enabled)}}}else if let e=store.operationError{Text(e).foregroundStyle(.red).textSelection(.enabled)}}}
