import OperationsCore
import SwiftUI

struct DiscoverMarketView:View {
    @EnvironmentObject var store:ConsoleStore
    @State private var query="";@State private var discovery:MarketDiscoveryResult?;@State private var selectedMarketID:String?;@State private var selectedRepresentationID:String?;@State private var reviewPlan:MarketRegistrationPlan?;@State private var registeredSymbol:String?;@State private var error:String?
    private var selectedMarket:DiscoveredMarket?{discovery?.markets.first{$0.id==selectedMarketID} ?? (discovery?.markets.count==1 ? discovery?.markets.first:nil)}
    private var selectedRepresentation:MarketRepresentation?{selectedMarket?.representations.first{$0.id==selectedRepresentationID}}
    private var busy:Bool{store.activeOperationID != nil}
    var body:some View{VStack(alignment:.leading,spacing:14){
        Text("Discover Market").font(.largeTitle);Text("Identify a market, select its tradable representation, and add it to Fragarach.").foregroundStyle(.secondary)
        HStack{TextField("Market name, symbol, company, index, commodity, FX or crypto pair",text:$query).textFieldStyle(.roundedBorder).onSubmit{discover()};Button("Discover"){discover()}.buttonStyle(.borderedProminent).disabled(query.trimmingCharacters(in:.whitespaces).isEmpty||busy);if busy{ProgressView().controlSize(.small)}}
        if let error{ContentUnavailableView("Operation failed",systemImage:"exclamationmark.triangle",description:Text(error))}
        else if let discovery{if discovery.discoveryStatus=="PARTIAL"{HStack{Label(discovery.explanation,systemImage:"questionmark.circle").font(.headline).foregroundStyle(.orange);if discovery.explanation=="Did you mean Solana?"{Button("Confirm Solana"){query="Solana";discover()}.buttonStyle(.borderedProminent)}}};resultView(discovery)}
        else{ContentUnavailableView("Describe a market",systemImage:"map",description:Text("Try XAGUSD, Silver, Google, US30, NZDJPY, Bitcoin, or a listed symbol."))}
        Spacer(minLength:0)
    }.padding().sheet(item:$reviewPlan){plan in RegistrationReview(plan:plan,onConfirm:{confirm(plan)},onCancel:{reviewPlan=nil})}}
    @ViewBuilder private func resultView(_ result:MarketDiscoveryResult)->some View{
        if result.markets.isEmpty{UnknownMarketView(discovery:result)}
        else if result.markets.count==1,let market=result.markets.first{ScrollView{MarketDetail(market:market,selection:$selectedRepresentationID,registeredSymbol:registeredSymbol,onAdd:{reviewPlan=$0},onOpen:openExisting,onAcquire:continueToAcquire,onOpenInverse:openInverse).frame(maxWidth:.infinity,alignment:.leading)}}
        else{VStack(alignment:.leading,spacing:12){Text("Select the intended underlying market").font(.headline);Picker("Market",selection:$selectedMarketID){ForEach(result.markets){Text($0.underlyingMarket).tag(Optional($0.id))}}.pickerStyle(.segmented);if let market=selectedMarket{ScrollView{MarketDetail(market:market,selection:$selectedRepresentationID,registeredSymbol:registeredSymbol,onAdd:{reviewPlan=$0},onOpen:openExisting,onAcquire:continueToAcquire,onOpenInverse:openInverse)}}}}
    }
    private func discover(){discovery=nil;registeredSymbol=nil;error=nil;Task{await store.run(.discoverMarket(query:query));guard store.lastProcessResult?.exitCode==0,let text=store.lastProcessResult?.stdout,let data=text.data(using:.utf8),let decoded=try? JSONDecoder().decode(MarketDiscoveryResult.self,from:data)else{error=store.operationError ?? "Market discovery failed";return};discovery=decoded;selectedMarketID=decoded.markets.count==1 ? decoded.markets.first?.id:nil;let m=decoded.markets.count==1 ? decoded.markets.first:nil;selectedRepresentationID=m?.recommendation.symbol.isEmpty==false ? m?.representations.first(where:{$0.symbol==m?.recommendation.symbol})?.id:nil}}
    private func confirm(_ plan:MarketRegistrationPlan){reviewPlan=nil;Task{await store.run(.registerInstrument(candidate:plan.candidate));guard store.lastProcessResult?.exitCode==0 else{error=store.operationError ?? "Registration failed";return};registeredSymbol=plan.canonicalRegistrationSymbol}}
    private func openExisting(_ symbol:String){store.selectedTruthLaneID="\(symbol):D1";store.section = .truth}
    private func continueToAcquire(_ symbol:String){store.acquisitionAsset=symbol;store.section = .acquire}
    private func openInverse(_ symbol:String){query=symbol;discover()}
}

private struct MarketDetail:View{
    let market:DiscoveredMarket;@Binding var selection:String?;let registeredSymbol:String?;let onAdd:(MarketRegistrationPlan)->Void;let onOpen:(String)->Void;let onAcquire:(String)->Void;let onOpenInverse:(String)->Void
    private var selected:MarketRepresentation?{market.representations.first{$0.id==selection}}
    var body:some View{VStack(alignment:.leading,spacing:16){
        HStack(alignment:.top){VStack(alignment:.leading,spacing:5){Text(market.underlyingMarket).font(.title2.bold());Text(market.canonicalIdentity).font(.caption.monospaced()).foregroundStyle(.secondary);Text(market.description).foregroundStyle(.secondary)};Spacer();Text(market.marketType).padding(6).background(.quaternary,in:Capsule());Text("\(market.confidence)%").padding(6).background(.quaternary,in:Capsule());primaryAction}
        if let fx=market.fxOrientation{Panel("FX Pair Orientation"){Facts([("Ordered Identity",fx.orderedPair),("Base Currency",fx.baseCurrency),("Quote Currency",fx.quoteCurrency),("Orientation",fx.orientationState),("Direct Provider Symbol",fx.requestedProviderSymbol ?? "Not confirmed"),("Authoritative Inverse",fx.inversePair),("Inverse Provider Symbol",fx.inverseProviderSymbol ?? "Not confirmed"),("Evidence Source",fx.evidenceSource ?? "Not established")]);if fx.orientationState=="INVERSE_ONLY"{Label("The inverse market is not the same provider instrument. \(fx.orderedPair) cannot be acquired as direct evidence from \(fx.inverseProviderSymbol ?? fx.inversePair).",systemImage:"exclamationmark.triangle.fill").foregroundStyle(.orange);Button("Open \(fx.inversePair)"){onOpenInverse(fx.inversePair)}.buttonStyle(.borderedProminent)}}}
        GroupBox("Tradable Representations"){LazyVGrid(columns:[GridItem(.adaptive(minimum:240),spacing:10)],spacing:10){ForEach(market.representations){r in Button(action:{selection=r.id},label:{VStack(alignment:.leading,spacing:6){HStack{Text(r.representationType).font(.caption).foregroundStyle(.secondary);Spacer();Image(systemName:selection==r.id ? "checkmark.circle.fill":"circle")};Text(r.displayName).fontWeight(.semibold);Text(r.symbol).font(.title3.monospaced());Text(r.contractOrShareClass ?? r.exchange ?? "Venue unknown").font(.caption).foregroundStyle(.secondary);Text(r.registrationStatus).font(.caption)}.frame(maxWidth:.infinity,alignment:.leading).padding(10).background(selection==r.id ? Color.accentColor.opacity(0.12):Color.clear,in:RoundedRectangle(cornerRadius:8))}).buttonStyle(.plain)}}.padding(.vertical,4)}
        if let r=selected{TimeframeMatrix(lanes:r.timeframeLanes);LazyVGrid(columns:[GridItem(.adaptive(minimum:320),spacing:12)],spacing:12){Panel("Registration Recommendation"){Facts([("Symbol",r.symbol),("Type",r.representationType),("Status",r.registrationStatus),("Readiness",r.acquisitionReadiness)])};Panel("Provider Discovery"){Facts([("Provider",r.provider ?? "Unknown"),("Known Symbol",r.providerSymbol ?? "Unknown"),("Mapping",r.providerMappingStatus),("Entitlement","Unknown")])};Panel("Preliminary Metadata"){Facts([("Asset Class",market.assetClass),("Venue",r.exchange ?? "Unknown"),("Currency",r.currency ?? "Unknown"),("Timezone",market.metadata.timezone ?? "Unknown")])};Panel("Acquisition Readiness"){VStack(alignment:.leading,spacing:6){Text(r.acquisitionReadiness);ForEach(r.warnings,id:\.self){Label($0,systemImage:"exclamationmark.triangle").font(.caption)}}}}}
        if registeredSymbol != nil{Panel("Registration Complete"){Facts([("Registration Identifier",registeredSymbol!), ("Authority State","REGISTERED_NO_EVIDENCE"),("Registration Version","1"),("Provider Mapping State",selected?.providerMappingStatus ?? "Unknown")]);Button("Continue to Acquisition"){onAcquire(registeredSymbol!)}.buttonStyle(.borderedProminent)}}
    }.padding(.vertical,4)}
    @ViewBuilder private var primaryAction:some View{if let r=selected{if registeredSymbol==r.symbol{Button("Continue to Acquisition"){onAcquire(r.symbol)}.buttonStyle(.borderedProminent)}else if r.registrationStatus != "NOT_REGISTERED"{Button("Open Existing"){onOpen(r.symbol)}.buttonStyle(.borderedProminent)}else if let plan=r.registrationPlan{Button("Add to Fragarach"){onAdd(plan)}.buttonStyle(.borderedProminent)}}}
}

private struct RegistrationReview:View{let plan:MarketRegistrationPlan;let onConfirm:()->Void;let onCancel:()->Void;@Environment(\.dismiss) private var dismiss;var body:some View{VStack(alignment:.leading,spacing:16){Text("Review Registration").font(.title);Text("No mutation occurs until you confirm.").foregroundStyle(.secondary);Facts([("Underlying Market",plan.underlyingMarket),("Selected Representation",plan.selectedRepresentation),("Canonical Symbol",plan.canonicalRegistrationSymbol),("Display Name",plan.displayName),("Asset Class",plan.assetClass),("Instrument Type",plan.instrumentType),("Exchange / Venue",plan.exchangeOrVenue ?? "Unknown"),("Timezone",plan.timezone ?? "Unknown"),("Session Authority",plan.sessionAuthority),("Base Currency",plan.baseCurrency ?? "Unknown"),("Quote Currency",plan.quoteCurrency ?? "Unknown"),("Provider Mapping",plan.providerMappings.map{"\($0.provider): \($0.symbol) [\($0.state)]"}.joined(separator:", "))]);ForEach(plan.registrationWarnings,id:\.self){Label($0,systemImage:"exclamationmark.triangle")};HStack{Button("Cancel",role:.cancel){dismiss();onCancel()};Spacer();Button("Back"){dismiss()};Button("Confirm Registration"){dismiss();onConfirm()}.buttonStyle(.borderedProminent)}}.padding(24).frame(minWidth:620)} }
private struct Panel<C:View>:View{let title:String;@ViewBuilder let content:C;init(_ title:String,@ViewBuilder content:()->C){self.title=title;self.content=content()};var body:some View{GroupBox(title){content.frame(maxWidth:.infinity,alignment:.leading).padding(.vertical,4)}}}
private struct TimeframeMatrix:View{let lanes:[MarketTimeframeLane];var body:some View{GroupBox("Timeframe Lanes"){Grid(alignment:.leading,horizontalSpacing:24,verticalSpacing:8){GridRow{ForEach(["Timeframe","Provider Capability","Registration","Acquisition","Reason"],id:\.self){Text($0).font(.caption.bold()).foregroundStyle(.secondary)}};Divider().gridCellColumns(5);ForEach(lanes){lane in GridRow{Text(lane.timeframe).font(.body.monospaced().bold());Text(lane.providerCapability);Text(lane.registrationState);Text(lane.acquisitionReadiness);Text(lane.reason).font(.caption).foregroundStyle(.secondary)}}}.frame(maxWidth:.infinity,alignment:.leading).padding(.vertical,4)}}}
private struct UnknownMarketView:View{let discovery:MarketDiscoveryResult;var body:some View{GroupBox("No recognised market identity found"){VStack(alignment:.leading,spacing:12){Text(discovery.operatorGuidance);Text("Search attempted").font(.headline);ForEach(["Canonical markets","Tradable representations","Aliases","Company names","Index names","Commodity names","ISO currency pairs"],id:\.self){Label($0,systemImage:"checkmark")};Text("Corrected search guidance").font(.headline);ForEach(discovery.suggestedSearches,id:\.self){Text("• \($0)")}}.frame(maxWidth:.infinity,alignment:.leading).padding(.vertical,6)}}}
